apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentracker
  template:
    metadata:
      labels:
        app: opentracker
    spec:
      containers:
      - name: opentracker
        image: lednerb/opentracker-docker:latest
        ports:
        - containerPort: 6969
