apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-nodeport
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - protocol: TCP
      name: tcp
      port: 8080
      targetPort: 8080
      nodePort: 30080 
    - protocol: TCP
      name: tcp-2
      port: 6881
      targetPort: 6881
    - protocol: UDP
      name: udp
      port: 6881
      targetPort: 6881
